version: '3'

services:
  mongo:
    image: 'mongo'
    volumes:
      - ./data:/data/db

  express:
    stdin_open: true
    tty: true # Enables debugging capabilities when attached to this container.
    build: .
    labels:
      kompose.service.type: nodeport
    command: /bin/bash -c "if [ ! -d node_modules ] ; then npm install ; fi && npm run start"   
    working_dir: /app
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongo:27017/myapp
      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
    depends_on:
      - mongo
    ports:
      - 3000:3000
    volumes:
      - .:/app
  project-ui:
      build: 
        context: ./client
      ports:
        - 8080:8080 
        - 8081:8081
      tty: true
      stdin_open: true
      depends_on:
        - express
